---
title: "Final_Project_Code"
output: html_document
---
```{r setup}
#      knitr::opts_knit$set(root.dir = normalizePath("/home1/emmashih/490_cluster/analysis_data")) 
      knitr::opts_knit$set(root.dir = normalizePath("/home1/spoden/490_cluster/analysis_data")) 
```

```{r}
library(TCGAbiolinks)
library(maftools)
```

```{r}
clin_query <- GDCquery(project = "TCGA-SKCM",
data.category = "Clinical",
data.type = "Clinical Supplement",
data.format = 'SKCM Biotab')
# GDCdownload(clin_query)
clinical.BCRtab.all <- GDCprepare(clin_query)
clinicSKCM <- clinical.BCRtab.all$clinical_patient_skcm[-c(1,2),]
```

random plot
title: "Final_Project_Code"
output: html_document
---
```{r setup}
#      knitr::opts_knit$set(root.dir = normalizePath("/home1/emmashih/490_cluster/analysis_data")) 
      knitr::opts_knit$set(root.dir = normalizePath("/home1/spoden/490_cluster/analysis_data")) 
```

```{r}
library(TCGAbiolinks)
library(maftools)
```

```{r}
clin_query <- GDCquery(project = "TCGA-SKCM",
data.category = "Clinical",
data.type = "Clinical Supplement",
data.format = 'SKCM Biotab')
# GDCdownload(clin_query)
clinical.BCRtab.all <- GDCprepare(clin_query)
clinicSKCM <- clinical.BCRtab.all$clinical_patient_skcm[-c(1,2),]
```

boxplot of Breslow thickness across AJCC tumor stages (the one from the exit ticket but better verison)
```{r}
library(ggplot2)
library(dplyr)

# Clean the stage and Breslow columns
breslow_clean <- clinicSKCM %>%
  filter(
    !is.na(ajcc_pathologic_tumor_stage),
    !is.na(breslow_thickness_at_diagnosis),
    breslow_thickness_at_diagnosis > 0,
    !ajcc_pathologic_tumor_stage %in% c("[Not Available]", "[Discrepancy]", 
                                         "[Unknown]", ""),
    !breslow_thickness_at_diagnosis %in% c("[Not Available]", "[Unknown]", "")
  ) %>%
  mutate(
    breslow_thickness_at_diagnosis = as.numeric(breslow_thickness_at_diagnosis),
    # Simplify stage to I, II, III, IV (strip substage letters like IA, IIB, etc.)
    stage_simple = gsub("Stage ", "", ajcc_pathologic_tumor_stage),
    stage_simple = gsub("[ABC]$", "", stage_simple),
    stage_simple = factor(stage_simple, levels = c("I", "II", "III", "IV"))
  ) %>%
  filter(!is.na(stage_simple), !is.na(breslow_thickness_at_diagnosis))

ggplot(breslow_clean, aes(x = stage_simple, y = breslow_thickness_at_diagnosis, 
                           fill = stage_simple)) +
  geom_boxplot(outlier.shape = 21, outlier.alpha = 0.5) +
  scale_fill_manual(values = c("I" = "blue", "II" = "red", 
                                "III" = "pink", "IV" = "green")) +
  scale_y_log10() +   # log scale because Breslow thickness is right-skewed
  xlab("AJCC Tumor Stage") +
  ylab("Breslow Thickness at Diagnosis (mm, log scale)") +
  ggtitle("Tumor Invasion Depth Across SKCM Stages")
```

Patient count by stage and vital status
```{r}
library(ggplot2)
library(dplyr)

stage_survival <- clinicSKCM %>%
  filter(
    !is.na(ajcc_pathologic_tumor_stage),
    !ajcc_pathologic_tumor_stage %in% c("[Not Available]", "[Discrepancy]", 
                                         "[Unknown]", ""),
    !is.na(vital_status),
    !vital_status %in% c("[Not Available]", "[Unknown]", "")
  ) %>%
  mutate(
    stage_simple = gsub("Stage ", "", ajcc_pathologic_tumor_stage),
    stage_simple = gsub("[ABC]$", "", stage_simple),
    stage_simple = factor(stage_simple, levels = c("I", "II", "III", "IV")),
    vital_status = factor(vital_status, levels = c("Alive", "Dead"))
  ) %>%
  filter(!is.na(stage_simple))

ggplot(stage_survival, aes(x = stage_simple, fill = vital_status)) +
  geom_bar(position = "stack") +
  scale_fill_manual(
    values = c("Alive" = "pink", "Dead" = "seagreen"),
    name = "Vital Status"
  ) +
  xlab("AJCC Tumor Stage") +
  ylab("Number of Patients") +
  ggtitle("SKCM Patient Count and Survival Outcome by Tumor Stage") 
```

